# This is going to be a python script designed to add the next
# batch to the labelled ones
# It wont matter if they are unlabelled because our app script
# only reads the unlablled ones
# To have control of the labelled ones we are going to put the version of the rules
# that each of the sentences have been labelled with

# COMMENT:
# If the columns in the labelled csv changes, this script needs to change as well
# Our input pool of data are the split text after being analyzed by GNORM, it is the end of the data extraction pipeline
# Our output new batch is going to have the columns of the ids frame and the unlabelled pool
# Our output new pool of unlabelled will only have the columns of the original unlabelled dataframe

# -----------------------------------------------------------------
# Packages
import sys
import argparse
import os
import pandas as pd
from pathlib import Path

# -----------------------------------------------------------------
# Arguments
parser = argparse.ArgumentParser()

parser.add_argument("originalPool",
                    help = "name of the file where the pool of unlabelled sentences")
parser.add_argument("samplingFile",
                    help = "file with the pool samples and the selection information")
parser.add_argument("iter",
                    help = "number of the iteration of the AL loop this is going to be",
                    type = int)
parser.add_argument("-outUnlabelled",
                    help = "filename of the output file with the new pool of unlabelled sentences",
                    required = True)
parser.add_argument("-outBatch",
                    help = "filename of the new batch of sentencs to label",
                    required = True)
parser.add_argument("-errorids",
                    help = "filename of the ids that have not been found in the unlabelled dataframe, by default it would be saved in file 'notFoundIds.csv'",
                    default = "notFoundIds.csv")
parser.add_argument("-inter",
                    help = "if provided, it must be a folder that will store the intermidiate files generated by the script")

args = parser.parse_args()

# -----------------------------------------------------------------
# First checks
# Existence of provided files
if not os.path.isfile(args.originalPool):
    print(f"Error: file '{args.originalPool}' does not exist")
    sys.exit(1)
else:
    unlabel = pd.read_csv(args.originalPool)

    # Does the unlab csv have the neccessary columns
    if not all(column in unlabel.columns for column in ["pmid", "number", "text", "gene", "start", "end", "id", "uniprotid", "sa"]):
        print('Error: Columns "pmid", "number", "text", "gene", "start", "end", "id", "uniprotid" and "sa" must be in unlabelled dataframe')
        sys.exit(1)

if not os.path.isfile(args.samplingFile):
    print(f"Error: file '{args.samplingFile}' does not exist")
    sys.exit(1)
else:
    sampling = pd.read_csv(args.samplingFile)
    # Does the sampling file have the 3 neccessary columns?
    if not all(column in sampling.columns for column in ["pmid", "number", "selected"]):
        print('Error: Columns "pmid", "number" and "selecetd" must be in the samplingFile dataframe')
        sys.exit(1)

if args.inter:
    target_dir = Path(args.inter)

    # Check if path exists and if it's a file instead of a folder
    if target_dir.exists() and not target_dir.is_dir():
        print(f"Error: The path '{target_dir}' already exists but is a file.")
        sys.exit(1)

    # Create the folder if it doesn't exist
    if not target_dir.exists():
        target_dir.mkdir(parents = True, exist_ok = True)

# -----------------------------------------------------------------
# Body of the script
# First of all we need to extract the selected ids
id_pool_selected = sampling[sampling["selected"] == True][["pmid", "number"]]
id_pool_selected.drop_duplicates(inplace = True)
if args.inter: # If given, we will save these ids
    id_pool_selected.to_csv(os.path.join(args.inter, f"identifiers_selected_batch_iter{args.iter}.csv"), index = False)

# Extracting a dataframe with the ids from the unlabelled dataframe
# We will be checking as well if some id has been left out of the extraction
merged_ids = id_pool_selected.merge(unlabel,
                                    how = "left",
                                    on = ["pmid", "number"],
                                    indicator = True) # This way we can show which ids have not been found

if args.inter: # If given, we will save the merged dataframe
    merged_ids.to_csv(os.path.join(args.inter, f"ids_originalPool_merged_selectedids_iter{args.iter}.csv"), index = False)

new_batch = merged_ids[merged_ids["_merge"] == "both"].drop("_merge", axis = 1) # Take only the ids that are in both dataframes and drop the merge column
ids_not_found = merged_ids[merged_ids["_merge"] == "left_only"][id_pool_selected.columns] # Take the ids that are not in both dataframes and just take the wanted columns

# If we have some ids that are not found
if not ids_not_found.empty:
    ids_not_found.to_csv(args.errorids, index = False)

# Add Iteration column to the new batch dataframe
new_batch["ALIteration"] = args.iter

# Remove rows from the unlab dataframe
new_pool = unlabel.merge(id_pool_selected,
                         how = "left",
                         on = ["pmid", "number"],
                         indicator = True)

if args.inter: # If given, we will save the merged dataframe
    new_pool.to_csv(os.path.join(args.inter, f"ids_originalPool_merged_pool_iter{args.iter}.csv"), index = False)

new_pool = new_pool[new_pool["_merge"] == "left_only"].drop("_merge", axis = 1)[unlabel.columns]

# Save new dataframes with the given names
new_batch.to_csv(args.outBatch, index = False)
new_pool.to_csv(args.outUnlabelled, index = False)